Feature/#1 mypc 기능의 custom PC 페이지 구현
HARl803/mypc-service pull request #3
Opened 2024-07-25 03:59 UTC by cocorini

## 🗂️ 이슈 연결
- #{1}
- closes: #{1} 

</br>

## 📌 구현한 API
- 내 PC 등록 : `Post  /api/v1/pc`
- 등록된 내 PC 조회 : `Get  /api/v1/pc`
- 내 PC 삭제 : `Delete  /api/v1/pc/{id}`
- 내 PC 부품 수정 : `Patch  /api/v1/pc/{id}`

</br>

## 📝 작업 사항
- 유저는 내 PC 페이지를 통해 5개의 custom PC를 등록할 수 있다.
- 각각 PC 에는 내가 선택한 부품이 등록되는데, 이것은 부품 찾기 페이지에서 진행할 수 있다.
- PC 부품 변경은 PC에 대한 부분이므로, custom PC안의 내용으로 포함했다.

</br>

2024-07-27 04:16 UTC, fsm12 requested changes
코드는 전반적으로 잘 작성되어 있네요.
다만 특정 케이스 처리와 중복된 로직을 제거하는 게 더 좋을 것 같습니다!

2024-07-27 04:16 UTC, fsm12 commented on src/main/java/com/haribo/mypc_service/application/service/MyComputerServiceImpl.java
> +    }
커스텀 PC 목록이 없는 경우는 예외로 처리하기보다는, 빈 리스트를 반환하는 방식이 더 나을 듯 싶네요

2024-07-27 04:16 UTC, fsm12 commented on src/main/java/com/haribo/mypc_service/presentation/MakeMyComputerController.java
> +    }
여기서 `myComputerService.getMyComputerList(userId)` 메소드를 2번 호출하고 있는데 중복된 로직인 것 같아요.
한번 호출하고 변수에 저장해서 쓰는 편이 좋아보입니다.

2024-07-27 09:51 UTC, Dada-none approved these changes
부품 종류도 많고 낯선 mongoDB랑 연결하느라 고생하셨겠어요....수정해야 된다고 보이는 부분은 없었구요 있다고 해도 제 짬바로는 보이지가 않네요;; 
다만 한가지 궁금한 점은 MyComputerDto에 Setter 어노테이션을 광범위하게 설정 하셨던데 그 부분은 별도의 이유가 있나요?.?

2024-07-28 09:56 UTC, cocorini commented on src/main/java/com/haribo/mypc_service/application/service/MyComputerServiceImpl.java
> +    }
- "PC 목록이 없다는 것은 예외 처리를 할 만큼의 상황이 아니다." 로 이해하면 될까요..?
- 커스텀 에러를 만드는게 좋아보입니다. 해당 부분 수정할게요!

2024-07-28 09:57 UTC, cocorini commented on src/main/java/com/haribo/mypc_service/presentation/MakeMyComputerController.java
> +    }
- 그렇네요. myComputerList를 body에 담는 것으로 코드 수정하겠습니다~!

2024-07-28 10:04 UTC, cocorini commented
다영님 댓글 달고 싶은데, 이미 approval 해주셔서 여기다가 코멘트 남깁니다..!
우선 제가 Setter 주입을 가장 위에다가 설정한 이유는 초기에 필드 변수에 대한 확신이 없어서 그 때마다 Setter에 대한 생각을 해주는 불편함을 없애기 위함이고, 변수별로 @Setter 설정을 하는 경우에 코드가 지저분해보여서 dto 클래스 위에 Setter주입 하는 것을 선호하는 편입니다..!

2024-07-28 10:55 UTC, fsm12 commented on src/main/java/com/haribo/mypc_service/application/service/MyComputerServiceImpl.java
> +    }
네 맞습니다.

예외 처리는 다음 로직을 수행할 수 없거나 이후 로직에 치명적인 오류를 일으킬 수 있을 때, 프로그램의 실행을 중단시켜 비정상적인 흐름이 흘러가지 않도록 막는 방법입니다.

여기서 커스텀 PC 개수가 없는 경우는 예측 불가능한 경우라고 보긴 어렵습니다. 따라서 프로그램을 중단시키기 보다, 빈 리스트 등을 반환하는 방법을 통해 이후 로직을 유연하게 이어가는 방식이 더 맞을 것 같네요.

2024-07-30 01:51 UTC, dwd9999 commented on src/main/java/com/haribo/mypc_service/application/dto/MyComputerDto.java
> +@NoArgsConstructor
혹시 NoArgsConstructor가 필요한 부분이 있나요?

2024-07-30 01:54 UTC, dwd9999 commented on src/main/java/com/haribo/mypc_service/application/service/MyComputerServiceImpl.java
> +        } else throw new RuntimeException("유저의 커스텀 PC 목록이 텅~ 비어있네요!");
에러 처리 과정에서 ControllerAdvice와 ExceptionHandler를 사용해 별도의 파일로 관리하는 것이 편할 것 같아요!

2024-07-30 02:32 UTC, cocorini commented on src/main/java/com/haribo/mypc_service/application/service/MyComputerServiceImpl.java
> +        } else throw new RuntimeException("유저의 커스텀 PC 목록이 텅~ 비어있네요!");
Exception 부분은 커스텀으로 만들어서 관리하겠습니다!

2024-07-30 02:36 UTC, cocorini commented on src/main/java/com/haribo/mypc_service/application/dto/MyComputerDto.java
> +@NoArgsConstructor
기능 흐름상으로, 처음 customPC를 만들 때 PC 별명을 추가해서 생성할지 아니면 customPC 생성 버튼을 누른 이후에 PC 별명을 추가할지에 대해 고민하던 중에 작성한 코드를 수정하지 않았네요..
후자의 흐름대로 진행될거같아서 NoArgsConstructor는 지워야겠습니다.

2024-07-30 02:42 UTC, dwd9999 commented on src/main/java/com/haribo/mypc_service/application/dto/MyComputerDto.java
> +@NoArgsConstructor
넵~

2024-07-30 02:43 UTC, dwd9999 submitted a review, later dismissed

2024-07-30 02:45 UTC, Dada-none approved these changes, later dismissed

2024-08-01 03:34 UTC, closed without merging