Feature/be/4/parts
HARl803/mypc-service pull request #6
Opened 2024-08-02 05:41 UTC by cocorini

## 🗂️ 이슈 연결
- #4 
</br>

## 📌 구현한 API
- 부품 별 조회 기능 : `GET  /api/v1/parts`

</br>

## 📝 작업 사항
- FE와 협의한 response 데이터에 맞춰 부품 별 조회 및 반환 기능 구현

</br>

2024-08-02 06:47 UTC, fsm12 requested changes
고생 많으셨습니다.
수정 조금만 더 하시면 될 것 같습니다~

2024-08-02 06:47 UTC, fsm12 commented on src/main/java/com/haribo/mypc_service/presentation/AssemblePartsController.java
> +}
`return ResponseEntity.status(HttpStatus.OK).body(partsService.getAllParts(partsName));` 로 바꾸는게 나을 것 같습니다.

2024-08-02 06:47 UTC, fsm12 commented on src/main/java/com/haribo/mypc_service/presentation/response/parts/CpuResponse.java
> +}
위에서는 다 나눠서 해주셨는데 여기는 붙어져있네요?

2024-08-02 06:47 UTC, fsm12 commented on src/main/java/com/haribo/mypc_service/presentation/response/parts/CaseResponse.java
> +    public static class Case{
`_case`는 지역변수라 이 클래스에서만 쓴다는 의미인  `_`를 추가하기엔 어려울 것 같아요.
그리고 카멜케이스도 아니네요.

2024-08-02 06:48 UTC, cocorini commented on src/main/java/com/haribo/mypc_service/presentation/AssemblePartsController.java
> +}
네 수정하겠습니다!

2024-08-02 07:28 UTC, cocorini commented on src/main/java/com/haribo/mypc_service/presentation/response/parts/CpuResponse.java
> +}
네 수정하겠습니다!

2024-08-02 07:28 UTC, cocorini commented on src/main/java/com/haribo/mypc_service/presentation/response/parts/CaseResponse.java
> +    public static class Case{
pcCase 변수로 수정했습니다~!

2024-08-04 01:53 UTC, dwd9999 submitted a review, later dismissed
고생하셨습니다~

2024-08-04 01:53 UTC, dwd9999 commented on src/main/java/com/haribo/mypc_service/parts/application/service/PartsService.java
> +    <T> List<T> getAllParts(String partsName) ;
제네릭 사용하실때 extends 키워드 사용하시면 타입 안정성을 더 챙길수 있지 않을까 싶습니다~

2024-08-04 03:25 UTC, Dada-none reviewed
저 많은 부품들 전부 처리하시느라 고생하셨습니다,,,그런데 혹시 제품별로 제공되는 정보의 종류와 가짓수가 달라지는 경우에는 response 처리가 어떻게 되나용?.?

2024-08-04 07:30 UTC, cocorini commented on src/main/java/com/haribo/mypc_service/parts/application/service/PartsService.java
> +    <T> List<T> getAllParts(String partsName) ;
오..! 좋은 생각인 것 같습니다. 그렇게 하기 위해서는 PartsResponse를 만들고, 해당 클래스에서 각각의 파츠 클래스들을 상속받은 뒤에 <T extends PartsResponse> 의 형식으로 활용해야 할까요?

2024-08-04 07:31 UTC, cocorini commented
> 저 많은 부품들 전부 처리하시느라 고생하셨습니다,,,그런데 혹시 제품별로 제공되는 정보의 종류와 가짓수가 달라지는 경우에는 response 처리가 어떻게 되나용?.?

이러한 경우에는, 아무래도 ResponseDto의 코드를 수정해야하는 번거로움이 있을 것 같습니다! 다만, 변수로 선언하는 사항들이 늘기는 하겠지만 줄어들일은 없기 때문에 어려운 부분은 아닐 것이라 생각합니다.

2024-08-04 22:05 UTC, dwd9999 commented on src/main/java/com/haribo/mypc_service/parts/application/service/PartsService.java
> +    <T> List<T> getAllParts(String partsName) ;
좋아용~

2024-08-08 07:09 UTC, dwd9999 approved these changes
LGTM~

2024-08-08 07:11 UTC, Dada-none approved these changes
간결한 코드 잘 봤습니다~고생하셨습니다~!

2024-08-08 07:26 UTC, fsm12 approved these changes
고생많으셨습니다

2024-08-09 16:14 UTC, merged